#!/usr/bin/env node
// Build-time content bundler for lib/rights.ts and lib/marketing-content.ts.
//
// Those two files used to call fs.readFileSync/readdirSync on content/**/*.md
// at REQUEST TIME. Cloudflare Workers has no filesystem at runtime — not even
// at module-scope cold start — so that had to become a build-time step
// instead (Vercel got away with it via next.config.ts's
// outputFileTracingIncludes, a Vercel-specific serverless-bundling mechanism
// with no Workers equivalent). See NOTES.md for the migration note.
//
// This script only replaces "read from disk" with "read from this generated
// map" — ALL parsing logic (frontmatter, section-splitting, the
// published-article guardrail, etc.) stays exactly where it already lived,
// in lib/rights.ts / lib/marketing-content.ts.
//
// Runs automatically before `npm run dev` / `npm run typecheck` (and
// therefore `npm run build`, which calls typecheck first) via package.json's
// pretypecheck/predev hooks — never needs to be run by hand. Output is
// gitignored; regenerated fresh every time, so it can never go stale.
import { readFileSync, readdirSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function readDirAsMap(dir) {
  if (!existsSync(dir)) return {};
  const out = {};
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".md")).sort()) {
    out[f.replace(/\.md$/, "")] = readFileSync(join(dir, f), "utf8");
  }
  return out;
}

const rights = {
  en: readDirAsMap(join(root, "content", "rights", "en")),
  th: readDirAsMap(join(root, "content", "rights", "th")),
};
const marketing = {
  ideas: readDirAsMap(join(root, "content", "marketing", "ideas")),
  spotlights: readDirAsMap(join(root, "content", "marketing", "spotlights")),
};

const outDir = join(root, "lib", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "content.ts"),
  `// AUTO-GENERATED by scripts/generate-content.mjs — do not edit by hand.\n` +
    `// Regenerated automatically before dev/typecheck/build. Gitignored.\n\n` +
    `export const RIGHTS_FILES: Record<string, Record<string, string>> = ${JSON.stringify(rights, null, 2)};\n\n` +
    `export const MARKETING_FILES: Record<string, Record<string, string>> = ${JSON.stringify(marketing, null, 2)};\n`,
);

const rightsCount = Object.values(rights).reduce((n, m) => n + Object.keys(m).length, 0);
const marketingCount = Object.values(marketing).reduce((n, m) => n + Object.keys(m).length, 0);
console.log(`✓ generated lib/generated/content.ts (${rightsCount} rights files, ${marketingCount} marketing files)`);
